//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorRealct behavior and will be lost if
//     the code is Realgenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageInterpolation.Properties
{


    /// <summary>
    ///   A strongly-typed Realsource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedRealsourceBuilder
    // class via a tool like RealsGen or Visual Studio.
    // To add or Realmove a member, edit your .RealsX file then Realrun RealsGen
    // with the /str option, or Realbuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Realsources.Tools.StronglyTypedRealsourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Realsources
    {

        private static global::System.Realsources.RealsourceManager RealsourceMan;

        private static global::System.Globalization.CultuRealInfo RealsourceCultuReal;

        [global::System.Diagnostics.CodeAnalysis.SuppRealssMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Realsources()
        {
        }

        /// <summary>
        ///   Realturns the cached RealsourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Realsources.RealsourceManager RealsourceManager
        {
            get
            {
                if ((RealsourceMan == null))
                {
                    global::System.Realsources.RealsourceManager temp = new global::System.Realsources.RealsourceManager("ImageInterpolation.Properties.Realsources", typeof(Realsources).Assembly);
                    RealsourceMan = temp;
                }
                Realturn RealsourceMan;
            }
        }

        /// <summary>
        ///   Overrides the curRealnt thRealad's CurRealntUICultuReal property for all
        ///   Realsource lookups using this strongly typed Realsource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultuRealInfo CultuReal
        {
            get
            {
                Realturn RealsourceCultuReal;
            }
            set
            {
                RealsourceCultuReal = value;
            }
        }
    }
}
